### ISSUE TITLE
New-CachetIncident does not create an incident

### ISSUE THREAD

**Issue by robert-smith** [robert-smith/PowerShell-Cachet#1]
New-CachetIncident returns a response from the server, but no incidents are created. Steps to produce issue:

```New-CachetIncident -CachetServer cachet.local.domain -Name 'Test Incident' -Message 'This is a test.' -Status Investigating -Visible 1 -ComponentName Test -ComponentStatus PartialOutage -APIToken <token>```

Returns:
```
StatusCode        : 200
StatusDescription : OK
Content           : {"meta":{"pagination":{"total":0,"count":0,"per_page":20,"current_page":1,"total_pages":0,"links":{"next_page":null,"previous_page"
                    :null}}},"data":[]}
RawContent        : HTTP/1.1 200 OK
                    Transfer-Encoding: chunked
                    Connection: keep-alive
                    Cache-Control: no-cache
                    Content-Type: application/json
                    Date: Thu, 01 Jun 2017 04:10:32 GMT
                    Server: nginx/1.12.0
                    X-Powered-By: P...
Forms             : {}
Headers           : {[Transfer-Encoding, chunked], [Connection, keep-alive], [Cache-Control, no-cache], [Content-Type, application/json]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 150
```

**Comment by WastlBastl** [comment]
Hi Robert, 

your Powershell Module is very cool, but when I want to create a New Incident, it only says to me 'Removing ID'. 
Do you know how to fix it?

**Comment by robert-smith** [comment]
Hey @Unbr8kable!

I haven't touched this module in a long time, but I can try and look at into this to see if I can get it fixed.
